const strings = {
    home :'Home',
    pomodoro:'Pomodoro',
    tasks:'Tasks',
    today:'Today',
    yesterday:'Yesterday',
    yourActivity:'Your Activity',
    uppercase:'uppercase',
    iHaveWorkedOn:`I've worked on...`,
    iWillBeWorkingOn:`I'll be working on...`,
    taskDescription:'Task Description',
    task:'Task',
    ready:'Ready',
    stop:'Stop',
    pause:'Pause',
    resume:'Resume',
    startSession:'Start session',
    focus:'Focus',
    enterHere:'Enter here...',
    taskCompletedSuccessfully:'Task Completed Successfully!',
    addTask:'Add Task',
    add:'Add',
    yes:'Yes',
    no:'No',
    timer:'Timer',
    doYouWantToEndTask:'Do you want to end task?',
    duration:'Duration',
    hours:'Hours',
    minutes:'Minutes',
    cancel:'Cancel',
    ok:'Ok',
    newTask:'New Task',
    oldTask:'Old Task',
    empty:'Keep track of your activities',
    boost:'Boost your productivity!',
    continue:'Continue',
    delete:'Delete',
    deleteActivity:'Delete Activity',
    done:'Done',
    taskDate:'Task Date',
    date:'date',
    thisWeek:'This week',
    all:'All',
    taskSummary:'Task summary',
    summaryByTags:'Summary By Tags',
    summaryByDays:'Summary By Days',
    enterTagsHere:'Enter tags here',
    tags:'Tags'
}

export default strings